### ISSUE TITLE
[explorer][750 USD] Advanced Search Page

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/tier-0-program#8]
**About This Project**

Core contains various endpoints for searching, e.g.:

- Blocks: https://api.ark.dev/public-rest-api/endpoints/blocks#search-all-blocks
- Transactions: https://api.ark.dev/public-rest-api/endpoints/transactions#search-for-transactions
- Wallets: https://api.ark.dev/public-rest-api/endpoints/wallets#search-all-wallets

For the explorer, we want to see a dedicated search page that utilizes what these endpoints bring. This means there should be options to search for blocks, transactions, and wallets based on the parameters that are allowed by the endpoints. Delegate search is not considered in this issue, as that is a better fit for the existing search field at the top of the explorer page as defined in ArkEcosystem/explorer#665.

> The difficulty level of this bounty is estimated as **intermediate**. The reward for completion of this project is set at **$750** (paid in ARK Ѧ).

_Requirements for completion:_
- Dedicated search page to search through blocks, transactions, and wallets
- Have proper inputs for the different types of search parameters so it’s easy for users to use them.
- Show a list of matching results that link to the corresponding explorer pages
- Proper tests that cover the newly added code

_Necessary Skills:_
- [TypeScript](https://www.typescriptlang.org/)
- [Vue.JS](https://vuejs.org)
- [Jest](https://jestjs.io/)
- [Cypress](https://www.cypress.io)

**Applying For This Project**

To apply for this project, please read more about the process below before leaving a comment with the following:

1. A brief proposal relating to the project (e.g. Your experience, how you wish to approach the project, estimated time to completion etc.)
2. Your name and a contact email address (or another form of contact, eg. Slack username) 

**The Process**

Applicant’s will only be permitted to participate in one Tier 0 project at any one time. You can apply for as many projects as you like, but will not be eligible to be accepted until your open projects have been completed. In the meantime the projects may be awarded to other available applicants.

If your application for the project is successful we'll contact you using the details you provided, assign the project to you and mark it as in progress. You'll be required to check in regularly with the ARK team to discuss progress and development. We'll also use these updates to ensure that the PR is being completed to a satisfactory standard. If we determine that the project isn't being completed to a satisfactory standard and that this cannot be achieved with minor amends or within a satisfactory timeframe, we hold the right to dismiss the PR and reopen the project to other applicants.

To deliver the project your PR must be submitted to the respective repo. ARK repo maintainers will then leave comments and request amends if necessary. All amends requested by maintainers must be resolved before completion, and all projects must comply with our code standards and contribution guidelines (found at: https://docs.ark.io/guidebook/contribution-guidelines/). After you've submitted your project, we'll review against the brief to ensure it meets the criteria and deliverables.

Once your project is approved as complete a member of the ARK team will follow up to discuss payment. You'll need to submit an invoice and payment will be issued in (Ѧ) ARK (equivalent to the USD reward value assigned to the project), sent to an address of your choosing. We may need to request additional information regarding your identity in order to comply with our own internal Know Your Customer (KYC) guidelines.

_If you're unsuccessful in applying for this particular project, please consider applying for others. Thanks for your interest and good luck with your application!_

**Comment by ItsANameToo** [comment]
Some additional information and designs:

Below is the design for the search page. It's quite a simple page as it consists of multiple fields to specify search criteria, a button to start the search and below will be a table with results that match the criteria. Some additional information:

- Input fields are similar to the ones in the desktop wallet, so those can be reused
- Search criteria depend on the endpoint. Please see the docs for the actual options. For the transaction endpoint the required parameters are given, for the other endpoints you can look them up (not every option will be relevant, if you're unsure something should be included then simply ask)
	- https://docs.ark.io/api/public/v2/wallets.html#search-all-wallets
	- https://docs.ark.io/api/public/v2/transactions.html#search-for-transactions
	- https://docs.ark.io/api/public/v2/blocks.html#search-all-blocks
- The search page has an input for the (expected) mostly used field e.g. id for a transaction / block, and should have wallet addresses for wallets. The others will be under "additional parameters", but keep in mind that every input field needs to be optional.
- With vendorfield you will need to make it into the hex value for the API as it expects a vendorFieldHex parameter instead. You might want to play around with that a bit to see how it works in practice.
- Results will be a simple table with pagination like the rest of the explorer has. You can reuse the pagination component for that and look at how the other tables are created (basically defining columns and a template to show them). The result table will be different based on what the user is searching for (e.g. wallets / blocks / transactions) and should contain all relevant information in it.
- Regarding responsiveness: the input fields should wrap on smaller screens, for mobile it's likely that you will end up with 1 input per "row" that takes full width. For the result table I'm unsure at the moment what the best approach is; either go with hiding least-informative columns like we do with other tables (as all information can be seen anyway when a user clicks on a transaction id) and list them below each other on mobile, or it might be interesting to have a table here that scrolls to the side to not lose out on any information.

![search_page](https://user-images.githubusercontent.com/35610748/66253351-48c49000-e767-11e9-9a92-735e6aeb5d32.png)
![search_page_dropdown](https://user-images.githubusercontent.com/35610748/66253352-4b26ea00-e767-11e9-9d1c-7b5f2c91be8e.png)

**Comment by Lemii** [comment]
I'd like to apply for this bounty, if it is still open.

As the author of the original [ARK Transaction Search](https://arkrelay.com/transaction-search) tool I have experience with achieving the goal set out in this tier-0 project. It also was the first tool that made searching the `vendorField` possible.

Even though I mostly work with React, I believe that performing this task in Vue won't be a major issue due to the similarities between the two frameworks. 

I expect to have the project completed before the end of the year.

You can find me as 'lemii' in the ARK Ecosystem Slack.

**Comment by ItsANameToo** [comment]
You're in @Lemii !

Good luck and we'll be in touch
